[package]
org = "hansika"
name = "sanitizor"
version = "0.1.0"
distribution = "2201.12.10"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "mcp"
version = "1.0.0"
