[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "hubspot.marketing.forms"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "crm", "marketing", "forms"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.marketing.forms"

[build-options]
observabilityIncluded = true
