[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "smartsheet"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["smartsheet", "project-management", "task-automation", "workflow-automation", "spreadsheet-integration"] 
# icon = "icon.png" # TODO: Add icon
repository = "https://github.com/ballerina-platform/module-ballerinax-smartsheet"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
