[package]
distribution = "2201.9.3"
org = "ballerinax"
name = "openai.chat"
version = "4.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["AI/Chat", "OpenAI", "Cost/Paid", "GPT-4", "ChatGPT", "Vendor/OpenAI"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-openai.chat"

[build-options]
observabilityIncluded = true