[package]
org = "hansika"
name = "doc_generator"
version = "0.1.0"
distribution = "2201.13.0-20250927-204700-7b3ef131"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "mcp"
version = "1.0.0"
