[package]
org = "wso2"
name = "supabase_security_monitoring"
version = "0.1.0"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "supabase"
version = "0.1.0"
repository = "local"
