[package]
org = "wso2"
name = "regional_music_discovery"
version = "0.1.0"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "apple.music"
version = "0.1.0"
repository = "local"
