{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Spotify Web API",
    "description" : "This is a generated connector from [Spotify API v1](https://developer.spotify.com/documentation/web-api/) OpenAPI Specification. \nThrough the Spotify Web API, external applications retrieve Spotify content such as album data and playlists.\n",
    "version" : "0.1.0",
    "x-ballerina-display" : {
      "label" : "Spotify",
      "iconPath" : "icon.png"
    },
    "x-ballerina-init-description" : "The connector initialization requires setting the API credentials. \nPlease create a [Spotify account](www.spotify.com) and obtain tokens following [this guide](https://developer.spotify.com/documentation/general/guides/authorization-guide/). Configure required scopes when obtaining the tokens. \n"
  },
  "servers" : [ {
    "url" : "https://api.spotify.com/v1"
  } ],
  "tags" : [ {
    "name" : "category-playlists",
    "description" : "Playlists API"
  } ],
  "paths" : {
    "/me/playlists" : {
      "get" : {
        "tags" : [ "category-playlists" ],
        "summary" : "Get a List of Current User's Playlists",
        "description" : "Get a list of the playlists owned or followed by the current Spotify\nuser.",
        "operationId" : "getMyPlaylists",
        "security" : [ {
          "spotify_auth" : [ "playlist-read-private", "playlist-read-collaborative" ]
        } ],
        "x-ballerina-display" : {
          "label" : "My Playlists"
        }
      }
    },
    "/playlists/{playlistId}" : {
      "get" : {
        "tags" : [ "category-playlists" ],
        "summary" : "Get a Playlist",
        "description" : "Get a playlist owned by a Spotify user.",
        "operationId" : "getPlaylistById",
        "security" : [ {
          "spotify_auth" : [ ]
        } ],
        "x-ballerina-display" : {
          "label" : "Playlist By Id"
        }
      },
      "put" : {
        "tags" : [ "category-playlists" ],
        "summary" : "Change a Playlist's Details",
        "description" : "Change a playlist's name and public/private state. (The user must, of\ncourse, own the playlist.)",
        "operationId" : "updatePlaylist",
        "security" : [ {
          "spotify_auth" : [ "playlist-modify-public", "playlist-modify-private" ]
        } ],
        "x-ballerina-display" : {
          "label" : "Update Playlist"
        }
      }
    },
    "/playlists/{playlistId}/tracks" : {
      "get" : {
        "tags" : [ "category-playlists" ],
        "summary" : "Get a Playlist's Items",
        "description" : "Get full details of the items of a playlist owned by a Spotify user.",
        "operationId" : "getPlaylistTracks",
        "security" : [ {
          "spotify_auth" : [ ]
        } ],
        "x-ballerina-display" : {
          "label" : "Playlist Tracks"
        }
      },
      "put" : {
        "tags" : [ "category-playlists" ],
        "summary" : "Reorder or Replace a Playlist's Items",
        "description" : "Either reorder or replace items in a playlist depending on the request's parameters.\nTo reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request's body.\nTo replace items, include `uris` as either a query parameter or in the request's body.\nReplacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist.\n\n\n**Note**: Replace and reorder are mutually[...]",
        "operationId" : "reorderOrReplacePlaylistTracks",
        "security" : [ {
          "spotify_auth" : [ "playlist-modify-public", "playlist-modify-private" ]
        } ],
        "x-ballerina-display" : {
          "label" : "Reorder or Replace Tracks"
        }
      }
    },
    "/users/{userId}/playlists" : {
      "get" : {
        "tags" : [ "category-playlists" ],
        "summary" : "Get a List of a User's Playlists",
        "description" : "Get a list of the playlists owned or followed by a Spotify user.",
        "operationId" : "getPlayslistsByUserID",
        "security" : [ {
          "spotify_auth" : [ "playlist-read-private", "playlist-read-collaborative" ]
        } ],
        "x-ballerina-display" : {
          "label" : "Playlist By User Id"
        }
      },
      "post" : {
        "tags" : [ "category-playlists" ],
        "summary" : "Create a Playlist",
        "description" : "Create a playlist for a Spotify user. (The playlist will be empty until\nyou [add tracks](https://developer.spotify.com/documentation/web-api/reference/#endpoint-add-tracks-to-playlist).)",
        "operationId" : "createPlaylist",
        "security" : [ {
          "spotify_auth" : [ "playlist-modify-public", "playlist-modify-private" ]
        } ],
        "x-ballerina-display" : {
          "label" : "Create Playlist"
        }
      }
    },
    "/browse/new-releases" : {
      "get" : {
        "tags" : [ "category-browse" ],
        "summary" : "Get All New Releases",
        "description" : "Get a list of new album releases featured in Spotify (shown, for example, on a Spotify player's \"Browse\" tab).",
        "operationId" : "getNewReleses",
        "security" : [ {
          "spotify_auth" : [ ]
        } ],
        "x-ballerina-display" : {
          "label" : "Get New Releases"
        }
      }
    },
    "/browse/featured-playlists" : {
      "get" : {
        "tags" : [ "category-browse" ],
        "summary" : "Get All Featured Playlists",
        "description" : "Get a list of Spotify featured playlists (shown, for example, on a Spotify player's 'Browse' tab).",
        "operationId" : "getFeaturedPlaylists",
        "security" : [ {
          "spotify_auth" : [ ]
        } ],
        "x-ballerina-display" : {
          "label" : "Get Featured Playlists"
        }
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "spotify_auth" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://accounts.spotify.com/authorize",
            "tokenUrl" : "https://accounts.spotify.com/api/token",
            "scopes" : {
              "app-remote-control" : "Remote control playback of Spotify. This scope is currently available to Spotify iOS and Android SDKs.",
              "playlist-modify-private" : "Write access to a user's private playlists.",
              "playlist-modify-public" : "Write access to a user's public playlists.",
              "playlist-read-collaborative" : "Include collaborative playlists when requesting a user's playlists.",
              "playlist-read-private" : "Read access to user's private playlists.",
              "streaming" : "Control playback of a Spotify track. This scope is currently available to the Web Playback SDK. The user must have a Spotify Premium account.",
              "ugc-image-upload" : "Write access to user-provided images.",
              "user-follow-modify" : "Write/delete access to the list of artists and other users that the user follows.",
              "user-follow-read" : "Read access to the list of artists and other users that the user follows.",
              "user-library-modify" : "Write/delete access to a user's \"Your Music\" library.",
              "user-library-read" : "Read access to a user's library.",
              "user-modify-playback-state" : "Write access to a user’s playback state",
              "user-read-currently-playing" : "Read access to a user’s currently playing content.",
              "user-read-email" : "Read access to user’s email address.",
              "user-read-playback-position" : "Read access to a user’s playback position in a content.",
              "user-read-playback-state" : "Read access to a user’s player state.",
              "user-read-private" : "Read access to user’s subscription details (type of user account).",
              "user-read-recently-played" : "Read access to a user’s recently played tracks.",
              "user-top-read" : "Read access to a user's top artists and tracks."
            }
          }
        }
      }
    }
  }
}